dvbtee requires iconv for ISO6937 & ATSC text conversion
functions.cpp:25:10: fatal error: iconv.h: No such file or directory
 #include <iconv.h>
          ^~~~~~~~~
compilation terminated.
Makefile:542: recipe for target 'functions.lo' failed
make[2]: *** [functions.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
atsctext.cpp:43:10: fatal error: iconv.h: No such file or directory
 #include <iconv.h>
          ^~~~~~~~~
compilation terminated.
Makefile:542: recipe for target 'atsctext.lo' failed
make[2]: *** [atsctext.lo] Error 1