Revert "bump gnutls in case it matters, also rtmpdump needed a bump as a result, a1900c3e15 works anyway building here"
This reverts commit e54114cd402855673e773a0f6a1b80a1c0f7c373.
I think this did a undefined reference to `mkstemp' for 64 bit for now